In [2]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv('cars.csv')

In [ ]:
df['brand']

32

1. OneHotEncoding using Pandas

In [12]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

2. K-1 OnehotEncoding

In [13]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

3. Onehotencoding using Sklearn

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=0)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(drop='first')
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()
# onehot encoding is done for the categorical variables fuel and owner. The drop='first' parameter is used to avoid the dummy variable trap.

In [ ]:
np.hstack([X_train[['brand','km_driven']].values, X_train_new]).shape

#p.hstack is used to horizontally stack the arrays. In this case, it combines the 'brand' and 'km_driven' columns from the training set with the one-hot encoded features for 'fuel' and 'owner'. The resulting shape of the combined array will reflect the total number of features after adding the one-hot encoded variables.

(6502, 9)

4.Onehotencoding with TopCategory

In [35]:
counts=df['brand'].value_counts()

In [37]:
df['brand'].nunique
threshold=100

In [39]:
repl= counts[counts<=threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(n=5)
#pd.get_dummies is used to perform one-hot encoding on the 'brand' column after replacing brands that occur less than or equal to the threshold (100) with the label 'uncommon'. This helps in reducing the number of unique categories in the 'brand' column, which can be beneficial for model performance and interpretability. The sample(n=5) method is used to display a random sample of 5 rows from the resulting DataFrame after one-hot encoding.

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3414,False,False,False,False,False,False,True,False,False,False,False,False,False
7402,False,False,False,False,True,False,False,False,False,False,False,False,False
5027,False,False,False,False,False,True,False,False,False,False,False,False,False
1547,False,False,False,False,False,True,False,False,False,False,False,False,False
6588,True,False,False,False,False,False,False,False,False,False,False,False,False